### ISSUE TITLE
亲，tf nmt 的文档什么时候能够整理完？

### ISSUE THREAD

**Issue by qujinqiang** [luozhouyang/csdn-blogs#1]
@luozhouyang  亲，如题，期待你能够尽快整理出来

**Comment by luozhouyang** [comment]
你好，我在阅读[tensorflow/nmt](https://github.com/tensorflow/nmt)代码的时候，觉得代码组织不是很好，目前在重构这个项目[luozhouyang/naivenmt](https://github.com/luozhouyang/naivenmt)，我准备把项目重构完之后，再来写完nmt的整个源码分析。
